### PR TITLE
Fix issue28

### PR DESCRIPTION
**Pull request by alexfauquette**
Now, modifying insight selection directly filter local state `questions` in order to remove unwanted questions.

It is also impossible to unselect the last selected insight type

### CODE REVIEW

**Review by hangy — APPROVED** [review]
works on my machine 🙂

**Review by ArnaudBarre — APPROVED** [review]
Ok ! 

I think this is good to avoid the "0" case,  and so now you can simplify the [0, 4] check l. 83

**Comment by alexfauquette** [comment]
Ok, I simply removed it

**Comment by ArnaudBarre** [comment]
No difference between send nothing or all 4 ? (In case a new category is created, no one will see it without a change in front no?)

**Comment by alexfauquette** [comment]
Hum... yes but if a new category is created, we should modify the front.

I think the best solution would be te replace the `insightTypes.js` by a call API which give the same information (the possibles insightTypes and its associated question)

**Pull request merged**
